"""
Django settings for cas2 project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
USE_X_FORWARDED_HOST = True
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&xxxxxx' # Key old cas

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'users-api.miurabox.com', 
    '0.0.0.0','localhost', 
    '127.0.0.1',
    'https://users.miurabox.info'
    'https://users.miurabox.info/',
    'http://users.miurabox.info/',
    'users-api.miurabox.info',
    'https://users-api.miurabox.info/',
    '193.168.10.1/8000',
    '193.168.10.1/9000'
]
#ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    'https://users.miurabox.info/',
    'http://users.miurabox.info/',
    'https://users.miurabox.info'
    '127.0.0.1',
    'http://localhost:4200',
    'http://localhost',
    'https://test-users.miurabox.com.mx',
    'https://users-api.miurabox.info/'
)

# Application definition
CORS_ALLOW_HEADERS = (
        'x-requested-with',
        'content-type',
        'content-disposition',
        'accept',
        'origin',
        'responseType',
        'authorization',
        'x-csrftoken',
        'Mimetype'
    )
    
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'middlewares',
    'accounts',
    'organizations',
    'core',
    'services',
    'django.contrib.humanize',
    'storages',
    #'django_celery_monitor',
    'apps',
    'multicotizador'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.authentication.verifyMiddleware'
]

ROOT_URLCONF = 'cas2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cas2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': 'usersdic2024',
        'NAME':'users11112025',
        # 'NAME':'saamusers2025',
        'USER': 'lupita',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',

    ),
    #'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

#USE_TZ = True

ACTIVATION_LINK = "https://users.miurabox.com/#/activate/"
ACTIVATION_LINK_USER = "https://users.miurabox.com/#/activate-user/"
# FORGET_PASSWORD_LINK = "https://users.miurabox.com/#/forgot-password/"
FORGET_PASSWORD_LINK = "http://127.0.0.1:4200/#/forgot-password/"

# SAAM_API_IP = "https://pre_api.miurabox.com/"
SAAM_API_IP = "http://127.0.0.1:8000/"
#MC_API_IP = "https://test_api.multicotizador.com/"
MC_API_IP = "https://grupoasapi.multicotizador.com/"
OLD_SAAM_API_IP ="https://pre_api.miurabox.com/"
PAYMENT_API_IP = "http://payment.mbservicios.com/"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# CELERY STUFF
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Mexico_City'
CELERY_BROKER_URL='redis://localhost:6379/0'


JWT_SECRET_KEY = 'CaS2.0S3cReTxxx'
JWT_ALGORITHM = 'HS256'
TOKEN_DURATION = 480
KEY_CAS = 'In73RN41K3yCa5'



# AMAZON
AWS_HEADERS = {  # see http://developer.yahoo.com/performance/rules.html#expires
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'Cache-Control': 'max-age=94608000',
}

# AWS_STORAGE_BUCKET_NAME = 'miurabox'
AWS_DEFAULT_ACL = None


AWS_STORAGE_BUCKET_NAME = 'miurabox'
AWS_ACCESS_KEY_ID = 'xxxxxxxx'
AWS_SECRET_ACCESS_KEY = 'xxxxxxxxxxxxxxxxxxxxx'
# Tell django-storages that when coming up with the URL for an item in S3 storage, keep
# it simple - just use this domain plus the path. (If this isn't set, things get complicated).
# This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
# We also use it in the next setting.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# This is used by the `static` template tag from `static`, if you're using that. Or if anything else
# refers directly to STATIC_URL. So it's safest to always set it.
# STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN

# Tell the staticfiles app to use S3Boto storage when writing the collected static files (when
# you run `collectstatic`).
# STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

# MEDIAFILES_LOCATION = 'cas_testing'
MEDIAFILES_LOCATION = 'cas'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MAIL_SERVICE = 'http://127.0.0.1:8001/'
BENEFICIOS_CONF = {
    'API_URL': SAAM_API_IP+'datavalidate'
    }




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS = True

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'no-reply@miurabox.com'
EMAIL_HOST_PASSWORD = 'xxxxxxxx'
